/**
 * AI summaries generated by the backend from a child's weekly behaviour data.
 *
 * The "parent_weekly" type is a short, parent-facing recap surfaced on the
 * dashboard AI Insights card.
 */

export type AiSummaryType = 'parent_weekly' | string;

export type AiSummarySeverity = 'low' | 'medium' | 'high' | null;

/** Raw summary object exactly as returned under `data.summary` by the API. */
export interface ApiAiSummary {
  uuid: string;
  type: AiSummaryType;
  language: string;
  title: string;
  summary_text: string;
  action_text: string | null;
  severity: AiSummarySeverity;
  status: string;
  read_status: boolean;
  period_start: string;
  period_end: string;
  created_at: string;
}

/** Camel-cased, UI-ready summary used by components. */
export interface AiWeeklySummary {
  uuid: string;
  type: AiSummaryType;
  language: string;
  title: string;
  summaryText: string;
  actionText: string | null;
  severity: AiSummarySeverity;
  readStatus: boolean;
  periodStart: string;
  periodEnd: string;
  createdAt: string;
}
